server:
  servlet:
    contextPath: /UTILITY_API
  port: 8073
kai:
  name: UTILITY_API
  key: utilityc4anh7v3a
  threadName: UTILITY_API
  pollSize: 100
  error:
    code996: "Error insert request to DB#{0}"
    code997: "Cannot be processed"
    code998: "Timeout {0}"
    code999: "Internal Server Error {0}"
    code801: "Request type not valid"
    code802: "Problem with calculating timeout or sendtime in request type 'response'"
    code803: "RequestId not exist"
    code804: "Request lacks valid information: {0}"
    code805: "Problem with command in request type 'request'"
    code700: "API key not exists"
    code701: "API not exist"
    code600: "Problem in mapper object"
    code503: "Failed to read from the database#{0}"
    code505: "Failed to call api#{0}"
    code333: "Don't have method validate for AuthenType"

spring:
  application:
    name: KAIASIA_UTILITY_API
  config:
    import: optional:file:application.yml
  database:
    postgres: true
  postgredatasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://14.225.254.212:5432/KAI_API?currentSchema=utility_api
    username: utility
    password: utility@kaiasia
    maximum-pool-size: 50
    idleTimeout: 120000
    minimumIdle: 10
  jpa:
    show-sql: false
    open-in-view: false
  redis:
    host: 14.225.254.212
    port: 6379
    timeout: 60000
    lettuce:
      pool:
        max-active: 7 #max kết nối
        max-idle: 3 #max kết nối rảnh
        min-idle: 1 #min kết nối auto hoạt động
#eureka:
#  client:
#    service-url:
#      defaultZone: http://14.225.254.212:8761/eureka

dbinfo:
  apiRequest: request_in
  apiResponse: request_out
dep-api:
  t24utilsApi:
    apiName: T24_UTIL_API
    url: http://14.225.254.212:8082/T24_UTIL_API/process
    timeout: 60000
    apiKey: VDI0X1VUSUxfQVBJ